name: Build and check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run tests
        run: ./gradlew test
      - name: Run Ktlint check
        run: ./gradlew ktCh --continue
      - name: Upload test results
        uses: actions/upload-artifact@v3.1.0
        if: always()
        with:
          name: test-results
          path: build/test-results/test/
