name: CI

on:
  [push, pull_request]

jobs:
  Test-Runner:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout to current branch'
        uses: actions/checkout@v2
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      - name: 'Testing Application'
        run: ./gradlew test
      - name: 'Uploading test artifacts'
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-artifacts
          path: |
            ./build/test-results/test/*.xml
            ./build/reports/tests
      - name: 'Running KtLinter'
        run: ./gradlew ktCh --continue

  Test-Reporter:
    needs: Test-Runner
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout to current branch'
        uses: actions/checkout@v3
      - name: 'Downloading all artifacts'
        uses: actions/download-artifact@v3
      - name: 'Generating test report for Github actions'
        uses: dorny/test-reporter@v1.5.0
        with:
          name: 'Test Report: JUnit'
          path: ./test-artifacts/test-results/test/*.xml
          reporter: java-junit
